### ISSUE TITLE
[1.10.2] Not functioning and error messages appear

### ISSUE THREAD

**Issue by Nullga** [Monospark/SpongeMatchers#1]
Is it version incompatibility? I'm using spongeforge-1.10.2-2011-5.0.0-BETA-1570. Currently using the default example.hocon for testing.

`[02:26:40] [Server thread/ERROR] [Sponge/]: Could not pass InteractEntityEvent$Secondary$OffHand$Impl to org.spongepowered.mod.plugin.SpongeModPluginContainer@1651d167
java.lang.NoSuchMethodError: org.spongepowered.api.entity.Entity.getPassenger()Ljava/util/Optional;
    at org.monospark.spongematchers.matcher.sponge.EntityMatcher.fillMap(EntityMatcher.java:49) ~[EntityMatcher.class:?]
    at org.monospark.spongematchers.matcher.sponge.LivingMatcher.fillMap(LivingMatcher.java:21) ~[LivingMatcher.class:?]
    at org.monospark.spongematchers.matcher.sponge.PlayerMatcher.fillMap(PlayerMatcher.java:25) ~[PlayerMatcher.class:?]
    at org.monospark.spongematchers.matcher.sponge.PlayerMatcher.fillMap(PlayerMatcher.java:13) ~[PlayerMatcher.class:?]
    at org.monospark.spongematchers.matcher.sponge.SpongeObjectMatcher.matches(SpongeObjectMatcher.java:22) ~[SpongeObjectMatcher.class:?]
    at org.monospark.spongematchers.matcher.SpongeMatcher$3.matches(SpongeMatcher.java:96) ~[SpongeMatcher$3.class:?]
    at org.monospark.actioncontrol.config.ConfigRegistry.lambda$getConfigs$2(ConfigRegistry.java:33) ~[ConfigRegistry.class:?]
    at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source) ~[?:1.8.0_73]
    at java.util.HashMap$KeySpliterator.forEachRemaining(Unknown Source) ~[?:1.8.0_73]
    at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:1.8.0_73]
    at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:1.8.0_73]
    at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source) ~[?:1.8.0_73]
    at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:1.8.0_73]
    at java.util.stream.ReferencePipeline.collect(Unknown Source) ~[?:1.8.0_73]
    at org.monospark.actioncontrol.config.ConfigRegistry.getConfigs(ConfigRegistry.java:34) ~[ConfigRegistry.class:?]
    at org.monospark.actioncontrol.rule.ActionRule.handle(ActionRule.java:84) ~[ActionRule.class:?]
    at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) ~[RegisteredListener.class:1.10.2-2011-5.0.0-BETA-1570]
    at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:354) [SpongeModEventManager.class:1.10.2-2011-5.0.0-BETA-1570]
    at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:337) [SpongeModEventManager.class:1.10.2-2011-5.0.0-BETA-1570]
    at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:382) [SpongeModEventManager.class:1.10.2-2011-5.0.0-BETA-1570]
    at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:367) [SpongeModEventManager.class:1.10.2-2011-5.0.0-BETA-1570]
    at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:138) [SpongeImpl.class:1.10.2-2011-5.0.0-BETA-1570]
    at net.minecraft.network.NetHandlerPlayServer.func_147340_a(NetHandlerPlayServer.java:736) [me.class:?]
    at net.minecraft.network.play.client.CPacketUseEntity.func_148833_a(SourceFile:68) [iu.class:?]
    at net.minecraft.network.play.client.CPacketUseEntity.func_148833_a(SourceFile:12) [iu.class:?]
    at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:118) [PacketUtil.class:1.10.2-2011-5.0.0-BETA-1570]
    at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$0(SourceFile:39) [fl$1.class:?]
    at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [fl$1.class:?]
    at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_73]
    at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_73]
    at net.minecraft.util.Util.func_181617_a(SourceFile:45) [h.class:?]
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668) [MinecraftServer.class:?]
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [ld.class:?]
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
    at java.lang.Thread.run(Unknown Source) [?:1.8.0_73]
`

**Comment by Nullga** [comment]
I just noticed now that I thought I did post this to ActionControl but here instead accidentally. Sorry for the inconveniences...
